name: Build, Test and Deploy

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main # Déploiement uniquement lors d'un push sur `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint # Lancer l'étape de linting ici

      - name: Build project
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    needs: build
    if: success() # Cette condition garantit que l'étape 'test' ne s'exécute que si 'build' a réussi

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
